In [6]:
import numpy as np

In [8]:
a = np.array([1, 2, 3, 4])
a = zeros(10)  
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
a = arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
a = array([1, 2, 3, 4, 5, 6, 7, 8])
b = a[::-1]
print(a,b)

[1 2 3 4 5 6 7 8] [8 7 6 5 4 3 2 1]


In [12]:
a = arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a = [1,2,0,0,4,0]
b = nonzero(a)
b

(array([0, 1, 4]),)

In [14]:
a = random.randint(-30, 30, (3, 3, 3))
a

array([[[-12,  11,  29],
        [-22,  15, -20],
        [-18, -20, -18]],

       [[ 15, -26, -12],
        [ -8,  -2,   7],
        [-11, -16,  23]],

       [[ 24,  16,   0],
        [  1,  23,  26],
        [  2, -12,  11]]])

In [18]:
a = random.randint(-50, 50, (10, 10))
print(a)
maxi = amax(a)
mini = amin(a)
maxi, mini

[[  4  23 -22 -27   6 -47  34 -10 -34  32]
 [  7 -28 -23 -21  35  -6 -33  43 -25  -5]
 [  9  -9 -25  27 -20 -22  46 -32  14 -16]
 [-41  12 -45  -6  20 -15  38 -14 -27  29]
 [ 33  31  -5  25 -44  42  23  30 -40  32]
 [-45 -45 -27 -20  24  35 -20  19 -42  12]
 [-11 -41 -32 -26 -33 -13 -23  49 -36 -34]
 [  9  42 -13 -20  45  23 -17  24  27   1]
 [ 10 -48  45  -7   2   7   6  21  -9 -12]
 [  9  13 -12 -44   2 -36  23 -32  -7 -19]]


(49, -48)

In [19]:
a = random.randint(1, 100, (30))
a

array([29, 93, 28, 88, 55, 58, 62, 30, 38,  1, 96, 59, 56, 51,  2, 61, 14,
       79, 45,  3, 13, 97, 74,  8, 20,  8, 86, 65, 99, 10])

In [20]:
a1 = mean(a)
a1

47.6

In [23]:
a = ones((5,5))
print(a, '\n')
a [1: -1, 1: -1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
a = tile(array([[1, 0], [0, 1]]), (4, 4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [27]:
a = arange(25).reshape(5, 5)                                
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print(a)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


In [29]:
a = array([1, 2, 3, 4, 5])                                          
a1 = array([3, 4, 5, 6, 7, 8])
a2 = intersect1d(a, a1)
a2

array([3, 4, 5])

In [31]:
a = zeros((5, 5))
a = a + arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [37]:
arr = linspace(0, 1, 12) 
a=arr[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])